<a href="https://colab.research.google.com/github/jefferson-spec/jeeh_data_science/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importa as bibliotecas
import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np

In [0]:
t = torch.Tensor([1,2,3])

In [0]:
t

tensor([1., 2., 3.])

In [0]:
a = np.array([1,2,3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

In [0]:
t * 10

tensor([10, 20, 30])

In [0]:
t ** 2

tensor([1, 4, 9])

In [0]:
t.dot(t)

tensor(14)

In [0]:
# importa datasets
data = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [0]:
data.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [0]:
X = data.drop('median_house_value', axis=1)
y = data['median_house_value']

In [0]:
class Net(nn.Module):

  def __init__(self):

    super(Net, self).__init__()

    
    self.fc1 = nn.Linear(8, 100)
    self.fc2 = nn.Linear(100, 100)
    self.out = nn.Linear(100, 1)

  def forward(self, x):
    x = F.normalize(x)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    
    y = self.out(x)

    return y

In [0]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=8, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=100, bias=True)
  (out): Linear(in_features=100, out_features=1, bias=True)
)


In [0]:
X_tensor = torch.from_numpy(data.values[:, :-1]).float()
y_tensor = torch.from_numpy(data.values[:, -1]).float()

y_tensor = torch.log(y_tensor) 

In [0]:
import torch.optim as optim

In [0]:
optimizer = optim.Adam(net.parameters(), lr=0.01)

In [0]:
criterion = nn.MSELoss()

In [0]:
for i in range(10):
  optimizer.zero_grad()
  prediction = net(X_tensor)
  loss = criterion(prediction, y_tensor)
  loss.backward()
  optimizer.step()

  prediction2 = torch.exp(net(X_tensor))
  loss = criterion(prediction2, torch.exp(y_tensor))
d  print('Monitor de loss:', torch.sqrt(loss))

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py:432: UserWarning: Using a target size (torch.Size([17000])) that is different to the input size (torch.Size([17000, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Monitor de loss: tensor(236235.4062, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(236058.9844, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(234138.9062, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(214015.7969, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(357230.2188, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(7039367., grad_fn=<SqrtBackward>)
Monitor de loss: tensor(22780980., grad_fn=<SqrtBackward>)
Monitor de loss: tensor(17899592., grad_fn=<SqrtBackward>)
Monitor de loss: tensor(6256297.5000, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(1445544.5000, grad_fn=<SqrtBackward>)


In [0]:
data_test = pd.read_csv("/content/sample_data/california_housing_test.csv")
data_test.head()



longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [0]:
X_test_tensor = torch.from_numpy(data_test.values[:, :-1]).float()
y_test = data_test.values[:, -1]


In [0]:
prediction_test = torch.exp(net(X_test_tensor))

In [0]:
print(prediction_test)

tensor([[ 910915.2500],
        [1540152.0000],
        [ 844589.8750],
        ...,
        [2016060.5000],
        [1593369.6250],
        [1009442.0000]], grad_fn=<ExpBackward>)


In [0]:
prediction_test_np = prediction_test.detach().numpy()
prediction_test_np

array([[ 910915.25],
       [1540152.  ],
       [ 844589.9 ],
       ...,
       [2016060.5 ],
       [1593369.6 ],
       [1009442.  ]], dtype=float32)

In [0]:
from sklearn.metrics import mean_squared_error
y_test = data_test.values[:, -1]
np.sqrt(mean_squared_error(y_test, prediction_test_np))

1478134.7022379986